name: 'Configuration Manager'
type: module
description: 'Allows importing and exporting configuration changes.'
package: Core
# version: VERSION
configure: config.sync

# Information added by Drupal.org packaging script on 2023-06-22
version: '10.1.0'
project: 'drupal'
datestamp: 1687424349
