name: Testing site config
type: profile
description: 'Minimal profile for testing with default site config.'
# version: VERSION
hidden: true

# Information added by Drupal.org packaging script on 2023-06-22
version: '10.1.0'
project: 'drupal'
datestamp: 1687424349
