name: Docker Drupal Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-docker@v1

      - name: Build and run Drupal container
        run: |
          docker run -d -p 8080:80 --name my-drupal \
            -v ${{ github.workspace }}/modules:/var/www/html/modules \
            -v ${{ github.workspace }}/profiles:/var/www/html/profiles \
            -v ${{ github.workspace }}/themes:/var/www/html/themes \
            -v ${{ github.workspace }}/sites:/var/www/html/sites \
            -e MYSQL_DATABASE=mydrupal \
            -e MYSQL_USER=root \
            -e MYSQL_PASSWORD=secret \
            -e MYSQL_HOST=mysql \
            drupal

      - name: Wait for Drupal container to start
        run: docker wait my-drupal

      - name: Display container logs
        run: docker logs my-drupal

