name: Docker Drupal Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Mysql database installation
        run:  |
          docker run -d --name mysqldatabase \
          -e MYSQL_ROOT_PASSWORD=secret \
          mysql:latest

          # Creating database
          docker exec -it mysqldatabase mysql -u root -psecret -e "CREATE DATABASE mydrupal;"

      - name: Run Drupal installation
        run: |
          docker run -d -p 8080:80 --name my-drupal --link mysqldatabase \
            -v ${{ github.workspace }}/modules:/var/www/html/modules \
            -v ${{ github.workspace }}/profiles:/var/www/html/profiles \
            -v ${{ github.workspace }}/themes:/var/www/html/themes \
            -v ${{ github.workspace }}/sites:/var/www/html/sites \
            -e MYSQL_DATABASE=mydrupal \
            -e MYSQL_USER=root \
            -e MYSQL_PASSWORD=secret \
            drupal:latest

          # Wait for Drupal container to start
          sleep 30

          # Install Drush using Composer
          docker exec my-drupal composer require drush/drush

          # Install Drupal using Drush
          docker exec my-drupal drush site:install --account-name=admin --account-pass=admin --db-url=mysql://root:secret@mysql/mydrupal

      - name: Display container logs
        run: docker logs my-drupal

      
