name: ci

on:
  push:
    branches:
      - "main"
jobs:
  build:
    runs-on: self-hosted
    steps:
        - name: checkout
          uses: actions/checkout@v2
        - name: Setup PHP with composer v2
          uses: shivammathur/setup-php@v2
          with:
            php-version: '8.1'
            tools: composer:v2
        - name: Setup Mysql database
          uses: docker run -d --name mysqldatabase -e MYSQL_ROOT_PASSWORD=root mysql:latest
        - name: Setup Drupal action
          uses: docker run -d --name drupalcontainer -p 8080:80 --link mysqldatabase -e MYSQL_USERNAME=root -e MYSQL_PASSWORD=root
      
