name: Docker Drupal Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Drupal installation
        run: |
          # Create a Docker network
          docker network create my-network
      
          # Start the MySQL container
          docker run -d --name mysqldatabase \
            --network my-network \
            -e MYSQL_DATABASE=mydrupal \
            -e MYSQL_USER=root \
            -e MYSQL_PASSWORD=secret \
            -e MYSQL_ROOT_PASSWORD=secret \
            mysql:latest
      
          # Start the Drupal container
          docker run -d -p 8080:80 --name my-drupal \
            --network my-network \
            -v ${{ github.workspace }}/modules:/var/www/html/modules \
            -v ${{ github.workspace }}/profiles:/var/www/html/profiles \
            -v ${{ github.workspace }}/themes:/var/www/html/themes \
            -v ${{ github.workspace }}/sites:/var/www/html/sites \
            -e MYSQL_DATABASE=mydrupal \
            -e MYSQL_USER=root \
            -e MYSQL_PASSWORD=secret \
            drupal:latest
      

     
          # Wait for Drupal container to start
          sleep 30

          # Install Drush using Composer
          docker exec my-drupal composer require drush/drush

      - name: Install Drupal using Drush
        run: |
          docker exec my-drupal drush site:install --account-name=admin --account-pass=admin --db-url=mysql://root:secret@mysqldatabase/mydrupal


          # Install Drupal using Drush
          docker exec my-drupal drush site:install --account-name=admin --account-pass=admin --db-url=mysql://root:secret@mysql/mydrupal

      - name: Display container logs
        run: docker logs my-drupal

      
