name: Docker Drupal Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Drupal installation
        run: |
          docker run -d -p 8080:80 --name my-drupal \
            -v ${{ github.workspace }}/modules:/var/www/html/modules \
            -v ${{ github.workspace }}/profiles:/var/www/html/profiles \
            -v ${{ github.workspace }}/themes:/var/www/html/themes \
            -v ${{ github.workspace }}/sites:/var/www/html/sites \
            -e MYSQL_DATABASE=mydrupal \
            -e MYSQL_USER=root \
            -e MYSQL_PASSWORD=secret \
            -e MYSQL_HOST=mysql \
            drupal

          # Wait for Drupal container to start
          sleep 30

          # Install Drush using Composer
          docker exec my-drupal composer require drush/drush

          # Install Drupal using Drush
          docker exec my-drupal drush site:install --account-name=admin --account-pass=admin --db-url=mysql://root:secret@mysql/mydrupal

      - name: Display container logs
        run: docker logs my-drupal

      - name: Clean up Docker resources
        run: docker rm my-drupal
