name: ci

on:
  push:
    branches:
      - "main"
jobs:
  build:
    runs-on: self-hosted
    steps:
        - name: checkout
          uses: actions/checkout@v2
        - name: Setup PHP with composer v2
          uses: shivammathur/setup-php@v2
          with:
            php-version: '8.1'
            tools: composer:v2
        - name: Setup Drupal action
          uses: docker://hussainweb/drupalqa:php8.1
      
